// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.10.1
//   protoc               v4.25.1
// source: shopping_copilot.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { TraceStep } from "./demo";

export const protobufPackage = "oteldemo";

/** Yêu cầu hội thoại */
export interface ChatWithCopilotRequest {
  /** ID của người dùng đang đăng nhập (để quản lý giỏ hàng) */
  userId: string;
  /** Câu hỏi hoặc câu lệnh của khách hàng */
  question: string;
  /**
   * DEPRECATED: lịch sử do client gửi lên nghĩa là client kiểm soát context của
   * LLM -- đường thẳng tới prompt injection. Dùng session_id, server tự nạp lịch
   * sử. Giữ field number 3 để không tái sử dụng nhầm.
   *
   * @deprecated
   */
  chatHistory: string[];
  /** Server tra lịch sử hội thoại theo session_id. Client không gửi context. */
  sessionId: string;
  /**
   * Khi user bấm "Đồng ý" trên Confirmation Gate, client gửi lại token này
   * (lấy từ PendingConfirmation.confirmation_token của lượt trước) để agent
   * thực thi đúng hành động ghi đã được duyệt.
   */
  confirmationToken: string;
}

/**
 * Hành động ghi (Tier 2 - ADR-006) đang chờ user xác nhận.
 * Agent KHÔNG được tự thực thi; nó trả về đây và dừng lại.
 */
export interface PendingConfirmation {
  /** vd "add_to_cart" */
  toolName: string;
  /** tham số đã chuẩn hoá, dạng JSON */
  argumentsJson: string;
  /** câu hỏi hiển thị cho user */
  humanPrompt: string;
  /** idempotency key, chống double-submit */
  confirmationToken: string;
  /** epoch giây; hết hạn thì phải hỏi lại */
  expiresAtUnix: number;
}

/** Một lời gọi tool đã thực thi -- phục vụ audit log (ADR-006). */
export interface ToolCallRecord {
  toolName: string;
  argumentsJson: string;
  succeeded: boolean;
  startedAtUnix: number;
  durationMs: number;
}

/**
 * Một review cụ thể mà Agent dùng làm nguồn cho câu trả lời (MANDATE-06/7a
 * tracing+citation trên UI -- cho phép reviewer kiểm chứng câu trả lời không
 * bịa, thay vì chỉ grep log).
 */
export interface Citation {
  /** id review trong reviews.productreviews */
  reviewId: string;
  /** trích đoạn description dùng làm nguồn */
  snippet: string;
  /** điểm số của review đó */
  score: string;
}

/** Phản hồi từ Agent */
export interface ChatWithCopilotResponse {
  /** Câu trả lời tổng hợp dạng text từ Agent */
  response: string;
  /**
   * Có giá trị <=> agent muốn thực thi một hành động ghi và đang chờ xác nhận.
   * Khi field này set, `response` chỉ là văn bản giải thích, KHÔNG có hành động
   * nào đã xảy ra.
   */
  pendingConfirmation:
    | PendingConfirmation
    | undefined;
  /** Mọi tool đã gọi trong lượt này. Frontend không cần dùng; tồn tại để truy vết. */
  actionsTaken: ToolCallRecord[];
  /** Agent trả lời từ fallback (LLM lỗi/timeout) thay vì model chính. */
  degraded: boolean;
  /**
   * OTel trace_id (hex, 32 ký tự) của lượt này -- tra trong Jaeger để xem toàn
   * bộ span con (Bedrock call, từng guardrail stage, từng tool call). Rỗng nếu
   * không có span đang active (vd. gọi ngoài context gRPC request).
   */
  traceId: string;
  /**
   * Review cụ thể agent dùng làm nguồn cho câu trả lời. Rỗng nếu câu trả lời
   * không dựa trên review nào (vd. câu hỏi về giá, hoặc "không có thông tin").
   */
  citations: Citation[];
  /** Dữ liệu từng bước cho UI trace panel */
  traceSteps: TraceStep[];
}

function createBaseChatWithCopilotRequest(): ChatWithCopilotRequest {
  return { userId: "", question: "", chatHistory: [], sessionId: "", confirmationToken: "" };
}

export const ChatWithCopilotRequest: MessageFns<ChatWithCopilotRequest> = {
  encode(message: ChatWithCopilotRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.question !== "") {
      writer.uint32(18).string(message.question);
    }
    for (const v of message.chatHistory) {
      writer.uint32(26).string(v!);
    }
    if (message.sessionId !== "") {
      writer.uint32(34).string(message.sessionId);
    }
    if (message.confirmationToken !== "") {
      writer.uint32(42).string(message.confirmationToken);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatWithCopilotRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatWithCopilotRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.question = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.chatHistory.push(reader.string());
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.sessionId = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.confirmationToken = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatWithCopilotRequest {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      question: isSet(object.question) ? globalThis.String(object.question) : "",
      chatHistory: globalThis.Array.isArray(object?.chatHistory)
        ? object.chatHistory.map((e: any) => globalThis.String(e))
        : [],
      sessionId: isSet(object.sessionId) ? globalThis.String(object.sessionId) : "",
      confirmationToken: isSet(object.confirmationToken) ? globalThis.String(object.confirmationToken) : "",
    };
  },

  toJSON(message: ChatWithCopilotRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.question !== "") {
      obj.question = message.question;
    }
    if (message.chatHistory?.length) {
      obj.chatHistory = message.chatHistory;
    }
    if (message.sessionId !== "") {
      obj.sessionId = message.sessionId;
    }
    if (message.confirmationToken !== "") {
      obj.confirmationToken = message.confirmationToken;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatWithCopilotRequest>, I>>(base?: I): ChatWithCopilotRequest {
    return ChatWithCopilotRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatWithCopilotRequest>, I>>(object: I): ChatWithCopilotRequest {
    const message = createBaseChatWithCopilotRequest();
    message.userId = object.userId ?? "";
    message.question = object.question ?? "";
    message.chatHistory = object.chatHistory?.map((e) => e) || [];
    message.sessionId = object.sessionId ?? "";
    message.confirmationToken = object.confirmationToken ?? "";
    return message;
  },
};

function createBasePendingConfirmation(): PendingConfirmation {
  return { toolName: "", argumentsJson: "", humanPrompt: "", confirmationToken: "", expiresAtUnix: 0 };
}

export const PendingConfirmation: MessageFns<PendingConfirmation> = {
  encode(message: PendingConfirmation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.toolName !== "") {
      writer.uint32(10).string(message.toolName);
    }
    if (message.argumentsJson !== "") {
      writer.uint32(18).string(message.argumentsJson);
    }
    if (message.humanPrompt !== "") {
      writer.uint32(26).string(message.humanPrompt);
    }
    if (message.confirmationToken !== "") {
      writer.uint32(34).string(message.confirmationToken);
    }
    if (message.expiresAtUnix !== 0) {
      writer.uint32(40).int64(message.expiresAtUnix);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PendingConfirmation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePendingConfirmation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.toolName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.argumentsJson = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.humanPrompt = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.confirmationToken = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.expiresAtUnix = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PendingConfirmation {
    return {
      toolName: isSet(object.toolName) ? globalThis.String(object.toolName) : "",
      argumentsJson: isSet(object.argumentsJson) ? globalThis.String(object.argumentsJson) : "",
      humanPrompt: isSet(object.humanPrompt) ? globalThis.String(object.humanPrompt) : "",
      confirmationToken: isSet(object.confirmationToken) ? globalThis.String(object.confirmationToken) : "",
      expiresAtUnix: isSet(object.expiresAtUnix) ? globalThis.Number(object.expiresAtUnix) : 0,
    };
  },

  toJSON(message: PendingConfirmation): unknown {
    const obj: any = {};
    if (message.toolName !== "") {
      obj.toolName = message.toolName;
    }
    if (message.argumentsJson !== "") {
      obj.argumentsJson = message.argumentsJson;
    }
    if (message.humanPrompt !== "") {
      obj.humanPrompt = message.humanPrompt;
    }
    if (message.confirmationToken !== "") {
      obj.confirmationToken = message.confirmationToken;
    }
    if (message.expiresAtUnix !== 0) {
      obj.expiresAtUnix = Math.round(message.expiresAtUnix);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PendingConfirmation>, I>>(base?: I): PendingConfirmation {
    return PendingConfirmation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PendingConfirmation>, I>>(object: I): PendingConfirmation {
    const message = createBasePendingConfirmation();
    message.toolName = object.toolName ?? "";
    message.argumentsJson = object.argumentsJson ?? "";
    message.humanPrompt = object.humanPrompt ?? "";
    message.confirmationToken = object.confirmationToken ?? "";
    message.expiresAtUnix = object.expiresAtUnix ?? 0;
    return message;
  },
};

function createBaseToolCallRecord(): ToolCallRecord {
  return { toolName: "", argumentsJson: "", succeeded: false, startedAtUnix: 0, durationMs: 0 };
}

export const ToolCallRecord: MessageFns<ToolCallRecord> = {
  encode(message: ToolCallRecord, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.toolName !== "") {
      writer.uint32(10).string(message.toolName);
    }
    if (message.argumentsJson !== "") {
      writer.uint32(18).string(message.argumentsJson);
    }
    if (message.succeeded !== false) {
      writer.uint32(24).bool(message.succeeded);
    }
    if (message.startedAtUnix !== 0) {
      writer.uint32(32).int64(message.startedAtUnix);
    }
    if (message.durationMs !== 0) {
      writer.uint32(40).int64(message.durationMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ToolCallRecord {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseToolCallRecord();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.toolName = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.argumentsJson = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.succeeded = reader.bool();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.startedAtUnix = longToNumber(reader.int64());
          continue;
        }
        case 5: {
          if (tag !== 40) {
            break;
          }

          message.durationMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ToolCallRecord {
    return {
      toolName: isSet(object.toolName) ? globalThis.String(object.toolName) : "",
      argumentsJson: isSet(object.argumentsJson) ? globalThis.String(object.argumentsJson) : "",
      succeeded: isSet(object.succeeded) ? globalThis.Boolean(object.succeeded) : false,
      startedAtUnix: isSet(object.startedAtUnix) ? globalThis.Number(object.startedAtUnix) : 0,
      durationMs: isSet(object.durationMs) ? globalThis.Number(object.durationMs) : 0,
    };
  },

  toJSON(message: ToolCallRecord): unknown {
    const obj: any = {};
    if (message.toolName !== "") {
      obj.toolName = message.toolName;
    }
    if (message.argumentsJson !== "") {
      obj.argumentsJson = message.argumentsJson;
    }
    if (message.succeeded !== false) {
      obj.succeeded = message.succeeded;
    }
    if (message.startedAtUnix !== 0) {
      obj.startedAtUnix = Math.round(message.startedAtUnix);
    }
    if (message.durationMs !== 0) {
      obj.durationMs = Math.round(message.durationMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ToolCallRecord>, I>>(base?: I): ToolCallRecord {
    return ToolCallRecord.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ToolCallRecord>, I>>(object: I): ToolCallRecord {
    const message = createBaseToolCallRecord();
    message.toolName = object.toolName ?? "";
    message.argumentsJson = object.argumentsJson ?? "";
    message.succeeded = object.succeeded ?? false;
    message.startedAtUnix = object.startedAtUnix ?? 0;
    message.durationMs = object.durationMs ?? 0;
    return message;
  },
};

function createBaseCitation(): Citation {
  return { reviewId: "", snippet: "", score: "" };
}

export const Citation: MessageFns<Citation> = {
  encode(message: Citation, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.reviewId !== "") {
      writer.uint32(10).string(message.reviewId);
    }
    if (message.snippet !== "") {
      writer.uint32(18).string(message.snippet);
    }
    if (message.score !== "") {
      writer.uint32(26).string(message.score);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Citation {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCitation();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.reviewId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.snippet = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.score = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Citation {
    return {
      reviewId: isSet(object.reviewId) ? globalThis.String(object.reviewId) : "",
      snippet: isSet(object.snippet) ? globalThis.String(object.snippet) : "",
      score: isSet(object.score) ? globalThis.String(object.score) : "",
    };
  },

  toJSON(message: Citation): unknown {
    const obj: any = {};
    if (message.reviewId !== "") {
      obj.reviewId = message.reviewId;
    }
    if (message.snippet !== "") {
      obj.snippet = message.snippet;
    }
    if (message.score !== "") {
      obj.score = message.score;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Citation>, I>>(base?: I): Citation {
    return Citation.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Citation>, I>>(object: I): Citation {
    const message = createBaseCitation();
    message.reviewId = object.reviewId ?? "";
    message.snippet = object.snippet ?? "";
    message.score = object.score ?? "";
    return message;
  },
};

function createBaseChatWithCopilotResponse(): ChatWithCopilotResponse {
  return {
    response: "",
    pendingConfirmation: undefined,
    actionsTaken: [],
    degraded: false,
    traceId: "",
    citations: [],
    traceSteps: [],
  };
}

export const ChatWithCopilotResponse: MessageFns<ChatWithCopilotResponse> = {
  encode(message: ChatWithCopilotResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.response !== "") {
      writer.uint32(10).string(message.response);
    }
    if (message.pendingConfirmation !== undefined) {
      PendingConfirmation.encode(message.pendingConfirmation, writer.uint32(18).fork()).join();
    }
    for (const v of message.actionsTaken) {
      ToolCallRecord.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.degraded !== false) {
      writer.uint32(32).bool(message.degraded);
    }
    if (message.traceId !== "") {
      writer.uint32(42).string(message.traceId);
    }
    for (const v of message.citations) {
      Citation.encode(v!, writer.uint32(50).fork()).join();
    }
    for (const v of message.traceSteps) {
      TraceStep.encode(v!, writer.uint32(58).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ChatWithCopilotResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseChatWithCopilotResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.response = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.pendingConfirmation = PendingConfirmation.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.actionsTaken.push(ToolCallRecord.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.degraded = reader.bool();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.traceId = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.citations.push(Citation.decode(reader, reader.uint32()));
          continue;
        }
        case 7: {
          if (tag !== 58) {
            break;
          }

          message.traceSteps.push(TraceStep.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ChatWithCopilotResponse {
    return {
      response: isSet(object.response) ? globalThis.String(object.response) : "",
      pendingConfirmation: isSet(object.pendingConfirmation)
        ? PendingConfirmation.fromJSON(object.pendingConfirmation)
        : undefined,
      actionsTaken: globalThis.Array.isArray(object?.actionsTaken)
        ? object.actionsTaken.map((e: any) => ToolCallRecord.fromJSON(e))
        : [],
      degraded: isSet(object.degraded) ? globalThis.Boolean(object.degraded) : false,
      traceId: isSet(object.traceId) ? globalThis.String(object.traceId) : "",
      citations: globalThis.Array.isArray(object?.citations)
        ? object.citations.map((e: any) => Citation.fromJSON(e))
        : [],
      traceSteps: globalThis.Array.isArray(object?.traceSteps)
        ? object.traceSteps.map((e: any) => TraceStep.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ChatWithCopilotResponse): unknown {
    const obj: any = {};
    if (message.response !== "") {
      obj.response = message.response;
    }
    if (message.pendingConfirmation !== undefined) {
      obj.pendingConfirmation = PendingConfirmation.toJSON(message.pendingConfirmation);
    }
    if (message.actionsTaken?.length) {
      obj.actionsTaken = message.actionsTaken.map((e) => ToolCallRecord.toJSON(e));
    }
    if (message.degraded !== false) {
      obj.degraded = message.degraded;
    }
    if (message.traceId !== "") {
      obj.traceId = message.traceId;
    }
    if (message.citations?.length) {
      obj.citations = message.citations.map((e) => Citation.toJSON(e));
    }
    if (message.traceSteps?.length) {
      obj.traceSteps = message.traceSteps.map((e) => TraceStep.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ChatWithCopilotResponse>, I>>(base?: I): ChatWithCopilotResponse {
    return ChatWithCopilotResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ChatWithCopilotResponse>, I>>(object: I): ChatWithCopilotResponse {
    const message = createBaseChatWithCopilotResponse();
    message.response = object.response ?? "";
    message.pendingConfirmation = (object.pendingConfirmation !== undefined && object.pendingConfirmation !== null)
      ? PendingConfirmation.fromPartial(object.pendingConfirmation)
      : undefined;
    message.actionsTaken = object.actionsTaken?.map((e) => ToolCallRecord.fromPartial(e)) || [];
    message.degraded = object.degraded ?? false;
    message.traceId = object.traceId ?? "";
    message.citations = object.citations?.map((e) => Citation.fromPartial(e)) || [];
    message.traceSteps = object.traceSteps?.map((e) => TraceStep.fromPartial(e)) || [];
    return message;
  },
};

/** Dịch vụ Shopping Copilot Agent */
export type ShoppingCopilotServiceService = typeof ShoppingCopilotServiceService;
export const ShoppingCopilotServiceService = {
  /** Thực hiện hội thoại với AI Agent */
  chatWithCopilot: {
    path: "/oteldemo.ShoppingCopilotService/ChatWithCopilot",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: ChatWithCopilotRequest): Buffer =>
      Buffer.from(ChatWithCopilotRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ChatWithCopilotRequest => ChatWithCopilotRequest.decode(value),
    responseSerialize: (value: ChatWithCopilotResponse): Buffer =>
      Buffer.from(ChatWithCopilotResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): ChatWithCopilotResponse => ChatWithCopilotResponse.decode(value),
  },
} as const;

export interface ShoppingCopilotServiceServer extends UntypedServiceImplementation {
  /** Thực hiện hội thoại với AI Agent */
  chatWithCopilot: handleUnaryCall<ChatWithCopilotRequest, ChatWithCopilotResponse>;
}

export interface ShoppingCopilotServiceClient extends Client {
  /** Thực hiện hội thoại với AI Agent */
  chatWithCopilot(
    request: ChatWithCopilotRequest,
    callback: (error: ServiceError | null, response: ChatWithCopilotResponse) => void,
  ): ClientUnaryCall;
  chatWithCopilot(
    request: ChatWithCopilotRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: ChatWithCopilotResponse) => void,
  ): ClientUnaryCall;
  chatWithCopilot(
    request: ChatWithCopilotRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: ChatWithCopilotResponse) => void,
  ): ClientUnaryCall;
}

export const ShoppingCopilotServiceClient = makeGenericClientConstructor(
  ShoppingCopilotServiceService,
  "oteldemo.ShoppingCopilotService",
) as unknown as {
  new (
    address: string,
    credentials: ChannelCredentials,
    options?: Partial<ClientOptions>,
  ): ShoppingCopilotServiceClient;
  service: typeof ShoppingCopilotServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
