# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shopping_copilot_pb2 as shopping__copilot__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shopping_copilot_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShoppingCopilotServiceStub:
    """Dịch vụ Shopping Copilot Agent
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatWithCopilot = channel.unary_unary(
                '/oteldemo.ShoppingCopilotService/ChatWithCopilot',
                request_serializer=shopping__copilot__pb2.ChatWithCopilotRequest.SerializeToString,
                response_deserializer=shopping__copilot__pb2.ChatWithCopilotResponse.FromString,
                _registered_method=True)


class ShoppingCopilotServiceServicer:
    """Dịch vụ Shopping Copilot Agent
    """

    def ChatWithCopilot(self, request, context):
        """Thực hiện hội thoại với AI Agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShoppingCopilotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatWithCopilot': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatWithCopilot,
                    request_deserializer=shopping__copilot__pb2.ChatWithCopilotRequest.FromString,
                    response_serializer=shopping__copilot__pb2.ChatWithCopilotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oteldemo.ShoppingCopilotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oteldemo.ShoppingCopilotService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShoppingCopilotService:
    """Dịch vụ Shopping Copilot Agent
    """

    @staticmethod
    def ChatWithCopilot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oteldemo.ShoppingCopilotService/ChatWithCopilot',
            shopping__copilot__pb2.ChatWithCopilotRequest.SerializeToString,
            shopping__copilot__pb2.ChatWithCopilotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
