# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shopping_copilot.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'shopping_copilot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import demo_pb2 as demo__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16shopping_copilot.proto\x12\x08oteldemo\x1a\ndemo.proto\"\x85\x01\n\x16\x43hatWithCopilotRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x18\n\x0c\x63hat_history\x18\x03 \x03(\tB\x02\x18\x01\x12\x12\n\nsession_id\x18\x04 \x01(\t\x12\x1a\n\x12\x63onfirmation_token\x18\x05 \x01(\t\"\x8b\x01\n\x13PendingConfirmation\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02 \x01(\t\x12\x14\n\x0chuman_prompt\x18\x03 \x01(\t\x12\x1a\n\x12\x63onfirmation_token\x18\x04 \x01(\t\x12\x17\n\x0f\x65xpires_at_unix\x18\x05 \x01(\x03\"|\n\x0eToolCallRecord\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02 \x01(\t\x12\x11\n\tsucceeded\x18\x03 \x01(\x08\x12\x17\n\x0fstarted_at_unix\x18\x04 \x01(\x03\x12\x13\n\x0b\x64uration_ms\x18\x05 \x01(\x03\"=\n\x08\x43itation\x12\x11\n\treview_id\x18\x01 \x01(\t\x12\x0f\n\x07snippet\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\t\"\x8e\x02\n\x17\x43hatWithCopilotResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12;\n\x14pending_confirmation\x18\x02 \x01(\x0b\x32\x1d.oteldemo.PendingConfirmation\x12/\n\ractions_taken\x18\x03 \x03(\x0b\x32\x18.oteldemo.ToolCallRecord\x12\x10\n\x08\x64\x65graded\x18\x04 \x01(\x08\x12\x10\n\x08trace_id\x18\x05 \x01(\t\x12%\n\tcitations\x18\x06 \x03(\x0b\x32\x12.oteldemo.Citation\x12(\n\x0btrace_steps\x18\x07 \x03(\x0b\x32\x13.oteldemo.TraceStep2r\n\x16ShoppingCopilotService\x12X\n\x0f\x43hatWithCopilot\x12 .oteldemo.ChatWithCopilotRequest\x1a!.oteldemo.ChatWithCopilotResponse\"\x00\x42\x13Z\x11genproto/oteldemob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shopping_copilot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021genproto/oteldemo'
  _globals['_CHATWITHCOPILOTREQUEST'].fields_by_name['chat_history']._loaded_options = None
  _globals['_CHATWITHCOPILOTREQUEST'].fields_by_name['chat_history']._serialized_options = b'\030\001'
  _globals['_CHATWITHCOPILOTREQUEST']._serialized_start=49
  _globals['_CHATWITHCOPILOTREQUEST']._serialized_end=182
  _globals['_PENDINGCONFIRMATION']._serialized_start=185
  _globals['_PENDINGCONFIRMATION']._serialized_end=324
  _globals['_TOOLCALLRECORD']._serialized_start=326
  _globals['_TOOLCALLRECORD']._serialized_end=450
  _globals['_CITATION']._serialized_start=452
  _globals['_CITATION']._serialized_end=513
  _globals['_CHATWITHCOPILOTRESPONSE']._serialized_start=516
  _globals['_CHATWITHCOPILOTRESPONSE']._serialized_end=786
  _globals['_SHOPPINGCOPILOTSERVICE']._serialized_start=788
  _globals['_SHOPPINGCOPILOTSERVICE']._serialized_end=902
# @@protoc_insertion_point(module_scope)
