{{- range $name, $config := .Values.components }}
{{- if and $config.enabled $config.serviceAccount $config.serviceAccount.create }}
{{- $serviceAccount := mergeOverwrite (deepCopy $.Values.serviceAccount) $config.serviceAccount }}
{{- $ctx := dict "Capabilities" $.Capabilities "Template" $.Template "name" ($name | lower) "Release" $.Release "Chart" $.Chart "serviceAccount" $serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "techx-corp.serviceAccountName" $ctx }}
  labels:
    {{- include "techx-corp.labels" $ctx | nindent 4 }}
  {{- if $serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := $serviceAccount.annotations }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}
