{{- if .Values.observabilityStorage.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.observabilityStorage.name }}
  labels:
    {{- include "techx-corp.labels" . | nindent 4 }}
provisioner: ebs.csi.aws.com
reclaimPolicy: {{ .Values.observabilityStorage.reclaimPolicy }}
volumeBindingMode: {{ .Values.observabilityStorage.volumeBindingMode }}
allowVolumeExpansion: {{ .Values.observabilityStorage.allowVolumeExpansion }}
parameters:
  {{- toYaml .Values.observabilityStorage.parameters | nindent 2 }}
{{- end }}
