{{- if .Values.prometheus.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: prometheus
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
---
{{- end }}
{{- if .Values.grafana.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: grafana
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
---
{{- end }}
{{- if .Values.jaeger.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: jaeger
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
{{- end }}
