{{- if .Values.thanos.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore
type: Opaque
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: {{ required "thanos.objectStorage.bucket is required" .Values.thanos.objectStorage.bucket | quote }}
      endpoint: s3.{{ required "thanos.objectStorage.region is required" .Values.thanos.objectStorage.region }}.amazonaws.com
      region: {{ .Values.thanos.objectStorage.region | quote }}
{{- end }}
