reloader:
  enabled: true # Bật auto-reload cho Sandbox

externalSecrets:
  enabled: true
  region: us-east-1
  secretPrefix: ecommerce-dev
  refreshInterval: 1h
  useProxyEndpoint: false # Giữ mặc định replica_endpoint cho Sandbox / Product-like
  serviceAccountName: external-secrets
  serviceAccountNamespace: external-secrets


