reloader:
  enabled: true # Bật auto-reload cho Sandbox

externalSecrets:
  enabled: true
  region: us-east-1
  secretPrefix: ecommerce-dev
  refreshInterval: 5m
  useProxyEndpoint: true # Bật Proxy endpoint cho Sandbox để test rotation & zero-downtime
  serviceAccountName: external-secrets
  serviceAccountNamespace: external-secrets


