apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develop-karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    repoURL: public.ecr.aws/karpenter
    chart: karpenter
    targetRevision: 1.14.0
    helm:
      skipCrds: true
      values: |
        settings:
          clusterName: ecommerce-develop-dev-eks
        serviceAccount:
          create: true
          name: karpenter
          annotations: {}
        controller:
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_DEFAULT_REGION
              value: us-east-1
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
