apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: develop-metrics-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    chart: metrics-server
    targetRevision: 3.12.2
    helm:
      values: |
        args:
          - --kubelet-insecure-tls
        resources:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            memory: 200Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
