# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_guard.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'ml_guard.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eml_guard.proto\x12\x10techx.mlguard.v1\"!\n\x11\x43heckInputRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"M\n\x12\x43heckInputResponse\x12\x0f\n\x07\x62locked\x18\x01 \x01(\x08\x12\x16\n\x0esanitized_text\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\"M\n\x12\x43heckOutputRequest\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x18\n\x10grounding_source\x18\x02 \x01(\t\x12\r\n\x05query\x18\x03 \x01(\t\"N\n\x13\x43heckOutputResponse\x12\x0f\n\x07\x62locked\x18\x01 \x01(\x08\x12\x16\n\x0esanitized_text\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\".\n\x16SanitizeReviewsRequest\x12\x14\n\x0cjson_payload\x18\x01 \x01(\t\"1\n\x17SanitizeReviewsResponse\x12\x16\n\x0esanitized_json\x18\x01 \x01(\t2\xad\x02\n\x0eMLGuardService\x12W\n\nCheckInput\x12#.techx.mlguard.v1.CheckInputRequest\x1a$.techx.mlguard.v1.CheckInputResponse\x12Z\n\x0b\x43heckOutput\x12$.techx.mlguard.v1.CheckOutputRequest\x1a%.techx.mlguard.v1.CheckOutputResponse\x12\x66\n\x0fSanitizeReviews\x12(.techx.mlguard.v1.SanitizeReviewsRequest\x1a).techx.mlguard.v1.SanitizeReviewsResponseBFZDgithub.com/nguyenductien-qnm/capstone-phase-3/techx-corp-platform/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_guard_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZDgithub.com/nguyenductien-qnm/capstone-phase-3/techx-corp-platform/pb'
  _globals['_CHECKINPUTREQUEST']._serialized_start=36
  _globals['_CHECKINPUTREQUEST']._serialized_end=69
  _globals['_CHECKINPUTRESPONSE']._serialized_start=71
  _globals['_CHECKINPUTRESPONSE']._serialized_end=148
  _globals['_CHECKOUTPUTREQUEST']._serialized_start=150
  _globals['_CHECKOUTPUTREQUEST']._serialized_end=227
  _globals['_CHECKOUTPUTRESPONSE']._serialized_start=229
  _globals['_CHECKOUTPUTRESPONSE']._serialized_end=307
  _globals['_SANITIZEREVIEWSREQUEST']._serialized_start=309
  _globals['_SANITIZEREVIEWSREQUEST']._serialized_end=355
  _globals['_SANITIZEREVIEWSRESPONSE']._serialized_start=357
  _globals['_SANITIZEREVIEWSRESPONSE']._serialized_end=406
  _globals['_MLGUARDSERVICE']._serialized_start=409
  _globals['_MLGUARDSERVICE']._serialized_end=710
# @@protoc_insertion_point(module_scope)
