# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ml_guard_pb2 as ml__guard__pb2

GRPC_GENERATED_VERSION = '1.82.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_guard_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLGuardServiceStub:
    """Service MLGuard defines the centralized policy engine for trust & safety.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CheckInput = channel.unary_unary(
                '/techx.mlguard.v1.MLGuardService/CheckInput',
                request_serializer=ml__guard__pb2.CheckInputRequest.SerializeToString,
                response_deserializer=ml__guard__pb2.CheckInputResponse.FromString,
                _registered_method=True)
        self.CheckOutput = channel.unary_unary(
                '/techx.mlguard.v1.MLGuardService/CheckOutput',
                request_serializer=ml__guard__pb2.CheckOutputRequest.SerializeToString,
                response_deserializer=ml__guard__pb2.CheckOutputResponse.FromString,
                _registered_method=True)
        self.SanitizeReviews = channel.unary_unary(
                '/techx.mlguard.v1.MLGuardService/SanitizeReviews',
                request_serializer=ml__guard__pb2.SanitizeReviewsRequest.SerializeToString,
                response_deserializer=ml__guard__pb2.SanitizeReviewsResponse.FromString,
                _registered_method=True)


class MLGuardServiceServicer:
    """Service MLGuard defines the centralized policy engine for trust & safety.
    """

    def CheckInput(self, request, context):
        """CheckInput applies jailbreak, PII detection, and prompt injection rules
        to user inputs before sending to the LLM.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckOutput(self, request, context):
        """CheckOutput validates LLM generated responses, evaluating grounding (hallucinations),
        output leaks, and returning sanitized/blocked text.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SanitizeReviews(self, request, context):
        """SanitizeReviews processes an untrusted JSON blob of product reviews,
        redacting PII and stripping malicious injections.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLGuardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CheckInput': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckInput,
                    request_deserializer=ml__guard__pb2.CheckInputRequest.FromString,
                    response_serializer=ml__guard__pb2.CheckInputResponse.SerializeToString,
            ),
            'CheckOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckOutput,
                    request_deserializer=ml__guard__pb2.CheckOutputRequest.FromString,
                    response_serializer=ml__guard__pb2.CheckOutputResponse.SerializeToString,
            ),
            'SanitizeReviews': grpc.unary_unary_rpc_method_handler(
                    servicer.SanitizeReviews,
                    request_deserializer=ml__guard__pb2.SanitizeReviewsRequest.FromString,
                    response_serializer=ml__guard__pb2.SanitizeReviewsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'techx.mlguard.v1.MLGuardService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('techx.mlguard.v1.MLGuardService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLGuardService:
    """Service MLGuard defines the centralized policy engine for trust & safety.
    """

    @staticmethod
    def CheckInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/techx.mlguard.v1.MLGuardService/CheckInput',
            ml__guard__pb2.CheckInputRequest.SerializeToString,
            ml__guard__pb2.CheckInputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/techx.mlguard.v1.MLGuardService/CheckOutput',
            ml__guard__pb2.CheckOutputRequest.SerializeToString,
            ml__guard__pb2.CheckOutputResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SanitizeReviews(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/techx.mlguard.v1.MLGuardService/SanitizeReviews',
            ml__guard__pb2.SanitizeReviewsRequest.SerializeToString,
            ml__guard__pb2.SanitizeReviewsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
