# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import shopping_copilot_pb2 as shopping__copilot__pb2


class ShoppingCopilotServiceStub(object):
    """Dịch vụ Shopping Copilot Agent
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ChatWithCopilot = channel.unary_unary(
                '/oteldemo.ShoppingCopilotService/ChatWithCopilot',
                request_serializer=shopping__copilot__pb2.ChatWithCopilotRequest.SerializeToString,
                response_deserializer=shopping__copilot__pb2.ChatWithCopilotResponse.FromString,
                )


class ShoppingCopilotServiceServicer(object):
    """Dịch vụ Shopping Copilot Agent
    """

    def ChatWithCopilot(self, request, context):
        """Thực hiện hội thoại với AI Agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShoppingCopilotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ChatWithCopilot': grpc.unary_unary_rpc_method_handler(
                    servicer.ChatWithCopilot,
                    request_deserializer=shopping__copilot__pb2.ChatWithCopilotRequest.FromString,
                    response_serializer=shopping__copilot__pb2.ChatWithCopilotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oteldemo.ShoppingCopilotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShoppingCopilotService(object):
    """Dịch vụ Shopping Copilot Agent
    """

    @staticmethod
    def ChatWithCopilot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/oteldemo.ShoppingCopilotService/ChatWithCopilot',
            shopping__copilot__pb2.ChatWithCopilotRequest.SerializeToString,
            shopping__copilot__pb2.ChatWithCopilotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
