apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-tunnel
  namespace: techx-tf1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflared-tunnel
  template:
    metadata:
      labels:
        app: cloudflared-tunnel
    spec:
      containers:
      - name: agent
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --url
        - http://frontend-proxy:8080
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
