apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techx-corp
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    # URL của git repository chứa mã nguồn của bạn
    repoURL: "https://github.com/nguyenductien-qnm/capstone-phase-3.git"
    targetRevision: feat/cdo-27-slo-dashboard-improve
    # Đường dẫn trỏ tới thư mục Helm Chart của bạn trong Git
    path: platform/charts/application

    # Cấu hình ArgoCD chạy Helm để sinh tài nguyên
    helm:
      valueFiles:
        - ../../gitops/environments/sandbox/values-flagd-sync.yaml
        - ../../gitops/environments/sandbox/values-ops-observability.yaml
        - ../../gitops/environments/sandbox/values-external-secrets.yaml
        # CI-managed image tags (app-build.yaml bump) — load CUỐI để override tag.
        - ../../gitops/environments/sandbox/values-image-tags.yaml

  destination:
    # URL API của cụm Kubernetes (nội bộ cụm)
    server: "https://kubernetes.default.svc"
    # Namespace muốn deploy ứng dụng lên
    namespace: techx-tf1

  syncPolicy:
    automated:
      prune: true # Tự động xóa các tài nguyên trên k8s nếu chúng bị xóa trên Git
      selfHeal: true # Tự động ghi đè lại nếu có ai sửa đổi cấu hình thủ công trên EKS
    syncOptions:
      - CreateNamespace=true # Tự động tạo namespace techx-tf1 nếu chưa có
