---
apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy-public
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: TCP
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: traffic-port
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: >-
      Environment=develop,ManagedBy=ArgoCD,Project=ecommerce-develop
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    opentelemetry.io/name: frontend-proxy
