apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicy
metadata:
  name: "deny-floating-image-tag"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods"]
    namespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
        - kube-system
        - kube-public
        - kube-node-lease
        - gatekeeper-system
        - argocd
  variables:
  - name: containers
    expression: 'object.spec.containers'
  - name: initContainers
    expression: 'has(object.spec.initContainers) ? object.spec.initContainers : []'
  - name: ephemeralContainers
    expression: 'has(object.spec.ephemeralContainers) ? object.spec.ephemeralContainers : []'
  - name: allContainers
    expression: 'variables.containers + variables.initContainers + variables.ephemeralContainers'
  validations:
  - expression: |
      variables.allContainers.all(c, 
        (!c.image.contains('/') ? 
          (c.image.contains(':') || c.image.contains('@')) : 
          (c.image.substring(c.image.lastIndexOf('/') + 1).contains(':') || c.image.substring(c.image.lastIndexOf('/') + 1).contains('@'))
        ) &&
        !['latest', 'dev', 'master', 'main', 'stable', 'edge'].exists(tag, c.image.endsWith(':' + tag))
      )
    messageExpression: |
      "container has disallowed image tag or no tag specified: " + 
      variables.allContainers.filter(c, 
        !((!c.image.contains('/') ? 
            (c.image.contains(':') || c.image.contains('@')) : 
            (c.image.substring(c.image.lastIndexOf('/') + 1).contains(':') || c.image.substring(c.image.lastIndexOf('/') + 1).contains('@'))
          ) && 
          !['latest', 'dev', 'master', 'main', 'stable', 'edge'].exists(tag, c.image.endsWith(':' + tag))
        )
      ).map(c, c.name + " (" + c.image + ")").join(", ")
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: "deny-floating-image-tag-binding"
spec:
  policyName: "deny-floating-image-tag"
  validationActions: [Deny]
